# -*- coding: utf-8 -*-
"""Modelos de datos declarativos del sistema de plantillas PDF."""

from .template import (
    ALINEACIONES,
    FUENTE_POR_DEFECTO,
    FUENTES_CATALOGO,
    LAYOUTS_SERVICIOS,
    LOGO_ALTO_MAX_CM,
    LOGO_ALTO_MIN_CM,
    MARGEN_MAX_CM,
    MARGEN_MIN_CM,
    ORIENTACIONES,
    POSICIONES_LOGO,
    SECCION_TIPOS,
    SECCIONES_BLOQUEADAS,
    TAMANO_FUENTE_MAX_PT,
    TAMANO_FUENTE_MIN_PT,
    TAMANOS_PAGINA,
    EncabezadoConfig,
    EstiloSeccion,
    PaginaConfig,
    PieConfig,
    SeccionConfig,
    TemaConfig,
    TemplateDefinition,
    migrar_definicion,
    validar_plantilla,
)

__all__ = [
    "ALINEACIONES",
    "FUENTE_POR_DEFECTO",
    "FUENTES_CATALOGO",
    "LAYOUTS_SERVICIOS",
    "LOGO_ALTO_MAX_CM",
    "LOGO_ALTO_MIN_CM",
    "MARGEN_MAX_CM",
    "MARGEN_MIN_CM",
    "ORIENTACIONES",
    "POSICIONES_LOGO",
    "SECCION_TIPOS",
    "SECCIONES_BLOQUEADAS",
    "TAMANO_FUENTE_MAX_PT",
    "TAMANO_FUENTE_MIN_PT",
    "TAMANOS_PAGINA",
    "EncabezadoConfig",
    "EstiloSeccion",
    "PaginaConfig",
    "PieConfig",
    "SeccionConfig",
    "TemaConfig",
    "TemplateDefinition",
    "migrar_definicion",
    "validar_plantilla",
]
